### ISSUE TITLE
URL bar and tabs inverted

### ISSUE THREAD

**Issue by elythh** [noriaku/firefox-monolite#6]
Hello, when using your theme on my device (Linux/NixOS), the tabs are at the top and under is he URL bar. I was wondering if that's the intended behaviour ? Since in the screenshots the URL bar is at the top.
Thank you

**Comment by noriaku** [comment]
Hey I just checked, and my configuration still correct... It should display in the following order: 

1. bookmarks
2. url bar
3. tab bar

This is because the following css:

```css
#PersonalToolbar {
    -moz-box-ordinal-group: 1 !important;
    padding-inline: 11px !important;
    color: var(--bg-sub-color);
}

#nav-bar {
    -moz-box-ordinal-group: 2 !important;
    color: var(--selected-color) !important;
}

#titlebar {
    color: var(--selected-color) !important;
    -moz-box-ordinal-group: 3 !important;
}
```

If it still doesn't work let me know, anyway you have an idea where to look (`-moz-box-ordinal-group`), check the lines from 164 to 179.

**Comment by noriaku** [comment]
Hey I just checked, and my configuration still correct... It should display in the following order: 

1. bookmarks
2. url bar
3. tab bar

This is because the following css:

```css
#PersonalToolbar {
    -moz-box-ordinal-group: 1 !important;
    padding-inline: 11px !important;
    color: var(--bg-sub-color);
}

#nav-bar {
    -moz-box-ordinal-group: 2 !important;
    color: var(--selected-color) !important;
}

#titlebar {
    color: var(--selected-color) !important;
    -moz-box-ordinal-group: 3 !important;
}
```

If it still doesn't work let me know, anyway you have an idea where to look (`-moz-box-ordinal-group`), check the lines from 164 to 179.
